### PR TITLE
Slight Fixes

### PR DESCRIPTION
**Pull request by DeathlyBower959**
Fixes:
 - Flicker on notification appear
 - Progress bar
 - Injection Speed

Additions:
 - Added the ability to add more icons for more events, like Christmas, Halloween, Hanukkah, etc.

### CODE REVIEW

**Comment by ftbento** [comment]
Could you check if I did the naming conventions correctly? If not either lmk what to change or change it yourself.

**Review by phasephasephase — CHANGES_REQUESTED** [review]
_bw, _value, and fadeSpeed in MainForm.cs should be renamed to bw, value, and _fadeSpeed

**Review by phasephasephase — CHANGES_REQUESTED** [review]
no rounding, it makes the design inconsistent

**Review by phasephasephase — APPROVED** [review]
gaming request

**Pull request merged**
