### PR TITLE
Added a cool looking discord-join button!

### PR DESCRIPTION
**Pull request by DerCooleVonDem**
That`s something that was definetly missing!

I tryed to stay close to the discord color palette and the onix-launcher design.

### CODE REVIEW

**Comment by DerCooleVonDem** [comment]
There are some large diffs but i didn`t changed them, guna and vs did -.-

**Review by phasephasephase — CHANGES_REQUESTED** [review]
would be pretty cool if controls were PascalCase and they had their type of control at the end of their names

also, could you send a screenshot of the launcher? i don't have any IDEs set up on my windows box atm

**Comment by DerCooleVonDem** [comment]
I will change that

**Comment by DerCooleVonDem** [comment]
Image of the launcher https://cdn.discordapp.com/attachments/925346393902694461/942777427216719953/unknown.png

**Comment by DerCooleVonDem** [comment]
Should be fixed now?

**Review by phasephasephase — COMMENTED** [review]
very nice

**Pull request merged**
